"""Pogi

Revision ID: ef282e200e96
Revises: 
Create Date: 2024-11-06 13:34:39.470733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef282e200e96'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Tour_Operator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_num', sa.String(length=15), nullable=True))

    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.alter_column('confirmed',
               existing_type=sa.VARCHAR(),
               type_=sa.Boolean(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.alter_column('confirmed',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('Tour_Operator', schema=None) as batch_op:
        batch_op.drop_column('contact_num')

    # ### end Alembic commands ###
